### PR TITLE
Prevented being able to fire the melondriver while swimming.

### PR DESCRIPTION
**Pull request by BClark09**
It will still fire if you land in water while shooting however.

### CODE REVIEW

**Comment by JetBoom** [comment]
That would stop people who are knee deep from firing as well. IsSwimming is a utility function that checks if water level is > 2.

**Comment by BClark09** [comment]
The problem is that if you hold jump and crouch whilst out of water then IsSwimming becomes false. I still like the ability to fire the driver mid-air but I'm unsure of a function that controls the movement of the player whilst in water.

**Comment by JetBoom** [comment]
GM:Move controls player movement as long as their move type isn't none or
vphysics (ie 100% of the time). I think I have it so pickups hook in to it
as well.

**Comment by BClark09** [comment]
```lua
function ENT:Move(pl, move)
	if self:GetFireTime() == 0 then
		move:SetMaxSpeed(move:GetMaxSpeed() * 0.7)
		move:SetMaxClientSpeed(move:GetMaxClientSpeed() * 0.7)
	else
		move:SetMaxSpeed(0)
		move:SetMaxClientSpeed(0)
		move:SetForwardSpeed(0)
		move:SetSideSpeed(0)
		move:SetUpSpeed(0)
	end
end
```

I'm not convinced it works when swimming, as you can move around freely in water even though forward speed should be zero. If you reach the bottom of the water, you stop immediately.

**Comment by JetBoom** [comment]
Weird then, I know the gamemode hook is called even when swimming so could be something else.

**Comment by BClark09** [comment]
This version should be fine.

**Pull request merged**
